server:
  port: 8080

spring:
  application:
    name: kcdAuthServer
  datasource:
    url: jdbc:mysql://localhost:3306/kcd
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  sql:
    init:
      platform: mysql
  # Hibernate 설정 - 테이블 자동 생성
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # http://localhost:8080/actuator 초기 id 및 비밀번호 (admin/password)
  security:
    user:
      name: admin
      password: "$2a$10$w45kxbj2Cf4Utr.KKjdr1uuqP1/MDcJXbn0JPxpp9VIG5MVA.oG2K"
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 2s
      timeout: 1s
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
